services:
  db:
    image: postgres:17
    container_name: ss-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ss-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 3s
      retries: 5

  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    container_name: ss-webapp
    environment:
      - DATABASE_URL=postgresql://root:root@db/postgres
      - IMAGE_STORE_PATH=/var/lib/back2u/images
      - CONFIGS_PATH=/var/lib/back2u/webapp-configs
      - DEFAULT_ADMIN_USER=admin
      - DEFAULT_ADMIN_PASS=admin
    volumes:
      - image_data:/var/lib/back2u/images
      - ./webapp-configs:/var/lib/back2u/webapp-configs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "8000:8000"
    networks:
      - ss-network

  rte:
    build:
      context: ./rte
      dockerfile: Dockerfile
    container_name: ss-rte
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ss-network

volumes:
  postgres_data:
  image_data:

networks:
  ss-network:
    driver: bridge