services:
  db:
    image: postgres:17
    container_name: ss-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ss-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 3s
      retries: 5

  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    container_name: ss-webapp
    environment:
      - DATABASE_URL=postgresql+psycopg2://root:root@ss-postgres:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "8000:8000"
    networks:
      - ss-network

  rte:
    build:
      context: ./rte
      dockerfile: Dockerfile
    container_name: ss-rte
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ss-network

  migrate:
    build:
      context: ./rte
      dockerfile: Dockerfile
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app/database
    networks:
      - ss-network

volumes:
  postgres_data:

networks:
  ss-network:
    driver: bridge