services:
  db:
    image: postgres:17
    container_name: ss-test-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - ss-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test"]
      interval: 3s
      retries: 5

  test-webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: ss-test-webapp
    environment:
      - DATABASE_URL=postgresql://root:root@db/test
    volumes:
      - ./webapp:/webapp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "8000:8000"
    networks:
      - ss-test-network
    command: ["python3", "-m", "unittest", "discover", "-s", "test", "-p", "int_*.py"]

networks:
  ss-test-network:
    driver: bridge