services:
  db:
    image: postgres:17
    container_name: ss-postgres-test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - ss-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 3s
      retries: 5

  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    container_name: ss-webapp-test
    environment:
      - DATABASE_URL=postgresql://root:root@db/postgres
      - IMAGE_STORE_PATH=/var/lib/back2u
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "8000:8000"
    networks:
      - ss-network
    command: ["python3", "-m", "unittest", "discover", "-s", "test", "-p", "unit_*.py"]

  # rte:
  #   build:
  #     context: ./rte
  #     dockerfile: Dockerfile
  #   container_name: ss-rte-test
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - ss-network

networks:
  ss-network:
    driver: bridge