services:
  db:
    image: postgres:17
    container_name: ss-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - ss-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 3s
      retries: 5

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: ss-webapp
    environment:
      - DATABASE_URL=postgresql://root:root@db/postgres
    volumes:
      - ./webapp:/webapp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "8000:8000"
    networks:
      - ss-network

  rte:
    build:
      context: ./rte
      dockerfile: Dockerfile
    container_name: ss-rte
    depends_on:
      - db
    networks:
      - ss-network

volumes:
  postgres_data:

networks:
  ss-network:
    driver: bridge