"""Add image_name column to Items table

Revision ID: 586e2d42703b
Revises: 4faad38ede6d
Create Date: 2025-06-20 19:53:30.969766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586e2d42703b'
down_revision: Union[str, None] = '4faad38ede6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_name', sa.String(length=16), nullable=True), schema='lost_found')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image_name', schema='lost_found')
    # ### end Alembic commands ###
