"""Add match_id column to ArchiveItems table

Revision ID: b91338d623cf
Revises: 586e2d42703b
Create Date: 2025-06-22 11:59:34.152000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91338d623cf'
down_revision: Union[str, None] = '4faad38ede6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archiveditems', sa.Column('match_id', sa.Integer(), nullable=False), schema='archive')
    #op.create_unique_constraint('uq_items_image_name', 'items', ['image_name'], schema='lost_found')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_items_image_name', 'items', schema='lost_found', type_='unique')
    #op.drop_column('archiveditems', 'match_id', schema='archive')
    # ### end Alembic commands ###
