"""Add last_submission, hashed passwords

Revision ID: ecc5d9287bfd
Revises: 8cb5eb03af9f
Create Date: 2025-06-23 22:35:35.095862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc5d9287bfd'
down_revision: Union[str, None] = '8cb5eb03af9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_submission', sa.DateTime(), nullable=True), schema='accounts')
    op.alter_column('accounts', 'password',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=False,
               schema='accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               schema='accounts')
    op.drop_column('accounts', 'last_submission', schema='accounts')
    # ### end Alembic commands ###
